INCLUDE_DIR=-I../.


example: example.cpp
	g++ -O3  $(INCLUDE_DIR) example.cpp -o example
ccArea: ccArea.cpp
	g++ -O3  $(INCLUDE_DIR) ccArea.cpp -o ccArea
simple_example: simple_example.cpp
	g++ -O3  $(INCLUDE_DIR) simple_example.cpp -o simple_example
