INCLUDE_DIR=-I../.


example: example.cpp
	g++ -O3  ${INCLUDE_DIR} example.cpp -o example
ccArea: ccArea.cpp
	g++ -O3 -fpermissive ${INCLUDE_DIR} ccArea.cpp -o ccArea
exemple_simple: exemple_simple.cpp
	g++ -O3 -fpermissive ${INCLUDE_DIR} exemple_simple.cpp -o exemple_simple
